### PR TITLE
Replace labels in Dialog

### PR DESCRIPTION
**Pull request by anasmi**
Replace Label component with Text. Suits better the purpose of the example

Fixes https://github.com/vaadin/90min-dx-tasks/issues/96

### CODE REVIEW

**Comment by tomivirkki** [comment]
Shouldn't the rest of the `Label`s also be replaced?

**Comment by anasmi** [comment]
@tomivirkki I can't change to Text, since it will break the tests https://github.com/vaadin/flow/issues/7686

Also, `Text` doesn't have an empty constructor, so Label seems more `nicer` here. Though, I agree this should be changed as well once the issue above is fixed

**Comment by anasmi** [comment]
@tomivirkki would this change be okay as this or should I change other labels to spans?

**Comment by tomivirkki** [comment]
Ah, I see. It's  fine then. Just a bit weird that for example in `addCloseFromServerSideDialog` the Label that's inside the Dialog is changed to Text, but the other label that's outside the Dialog (`messageLabel`) is still a Label.

Did you notice the suggested workaround: https://github.com/vaadin/flow/issues/7686#issuecomment-591425800

**Comment by anasmi** [comment]
Yes, noticed :) But replacing it in the demo file will also require tests adjustments, thus asking if you want me to do it, before actually implementing it :)

**Comment by tomivirkki** [comment]
The demo view should not be used for integration testing. This has been changed in many components already but I guess this one still does it. Should be changed. As such, this PR would fix https://github.com/vaadin/90min-dx-tasks/issues/96 only partially.

**Comment by anasmi** [comment]
@tomivirkki decoupled test and remove use of Labels from the demo altogether.

**Pull request merged**
