### PR TITLE
Update dialog to 2.0.2

### LINKED ISSUE #67: Placing a Grid into a dialog shows a grey vertical line by default
Code to reproduce the issue (vaadin 10 beta9):

```Dialog dialog = new Dialog();

       Grid<String> grid = new Grid<>();

       grid.addColumn(s ->"generated value").setHeader("generated column");
       grid.addColumn(s ->"second generated value").setHeader("generated column");
       grid.addColumn(s ->"third generated value").setHeader("generated column");
       grid.addColumn(s ->"fourth generated value").setHeader("generated column");

       dialog.add(grid);

       dialog.open();

```

With default settings something should be visible on the screen.

### PR DESCRIPTION
**Pull request by caalador**
Added test that empty dialog has size.

Fixes #67

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/71)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[src/test/java/com/vaadin/flow/component/dialog/tests/DialogTestPageIT.java, line 130 at r1](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/71#-LDFdTAV66KFL7UJrjGg:-LDFdTAV66KFL7UJrjGh:bw5rbhz) ([raw file](https://github.com/vaadin/vaadin-dialog-flow/blob/7f4214a8d9f00f53a2e81a1b4fb69dd40eb2da71/src/test/java/com/vaadin/flow/component/dialog/tests/DialogTestPageIT.java#L130)):*
> ```
>         Assert.assertTrue("Empty dialog didn't have a width",
>                 Integer.parseInt(element.getCssValue("width")) > 100);
> ```

Not exactly what's tested. The dialog should have at least 100px width according to the test.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/71)*

**Comment by caalador** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/test/java/com/vaadin/flow/component/dialog/tests/DialogTestPageIT.java, line 130 at r1](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/71#-LDFdTAV66KFL7UJrjGg:-LDFgPywDD8reTORr8Vt:b-2eq5zl) ([raw file](https://github.com/vaadin/vaadin-dialog-flow/blob/7f4214a8d9f00f53a2e81a1b4fb69dd40eb2da71/src/test/java/com/vaadin/flow/component/dialog/tests/DialogTestPageIT.java#L130)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
>         Assert.assertTrue("Empty dialog didn't have a width",
>                 Integer.parseInt(element.getCssValue("width")) > 100);
> ```

Not exactly what's tested. The dialog should have at least 100px width according to the test.
</blockquote></details>

Done.

Also might help to have `@Test` to actually run the test.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/71)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/test/java/com/vaadin/flow/component/dialog/tests/DialogTestPageIT.java, line 130 at r1](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/71#-LDFdTAV66KFL7UJrjGg:-LDFgiBz7nRBfBnGtX1p:bwf0ggl) ([raw file](https://github.com/vaadin/vaadin-dialog-flow/blob/7f4214a8d9f00f53a2e81a1b4fb69dd40eb2da71/src/test/java/com/vaadin/flow/component/dialog/tests/DialogTestPageIT.java#L130)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Done.

Also might help to have `@Test` to actually run the test.
</blockquote></details>

Sure :)

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/71#-:-LDFgmOV06656PXdKKrO:bnfp4nl)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/71#-:-LDGOmqI5-FTNfLj6VPC:bnfp4nl)*

**Pull request merged**
